name = "OORecheck"
defaultTargets = ["OneObstruction"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.34.0"

[[lean_lib]]
name = "OneObstruction"

[[lean_lib]]
name = "Labo"
